### ISSUE TITLE
Document developer-practices from the ffd-microsite

### ISSUE THREAD

**Issue by rogeruiz** [18F/ffd-toolkit#2]
With work starting on the Federal Front Door Microsite, there is workflow and documentation that would be valuable for this repo. This issue should be referenced in any PRs or Issues in [18f/ffd-microsite](https://github.com/18f/ffd-microsite) that should be brought into this project.

**Comment by juliasolorzano** [comment]
Closing this in favor for us creating smaller issues/tasks to tackle to achieve.
